// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVfUuSl-TCAwruiL13gY87F1XTgrP2fLw',
    appId: '1:243156572755:web:51e7200fb6f51e47f084a6',
    messagingSenderId: '243156572755',
    projectId: 'rotardv-af215',
    authDomain: 'rotardv-af215.firebaseapp.com',
    storageBucket: 'rotardv-af215.firebasestorage.app',
    measurementId: 'G-JVLS349NQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxkAg9TcEJ7rlMx_cDMI-ivfU5FZESpco',
    appId: '1:243156572755:android:726e01556fab5f37f084a6',
    messagingSenderId: '243156572755',
    projectId: 'rotardv-af215',
    storageBucket: 'rotardv-af215.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQFnAuwCWbOGp2SI02xQ1uJCl43oyRFL8',
    appId: '1:243156572755:ios:af64613bbc3076ddf084a6',
    messagingSenderId: '243156572755',
    projectId: 'rotardv-af215',
    storageBucket: 'rotardv-af215.firebasestorage.app',
    iosBundleId: 'com.example.appDespesas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQFnAuwCWbOGp2SI02xQ1uJCl43oyRFL8',
    appId: '1:243156572755:ios:af64613bbc3076ddf084a6',
    messagingSenderId: '243156572755',
    projectId: 'rotardv-af215',
    storageBucket: 'rotardv-af215.firebasestorage.app',
    iosBundleId: 'com.example.appDespesas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVfUuSl-TCAwruiL13gY87F1XTgrP2fLw',
    appId: '1:243156572755:web:11c169938403f93cf084a6',
    messagingSenderId: '243156572755',
    projectId: 'rotardv-af215',
    authDomain: 'rotardv-af215.firebaseapp.com',
    storageBucket: 'rotardv-af215.firebasestorage.app',
    measurementId: 'G-GNVD7ZCH1W',
  );
}
